[package]
name = "bluetooth_music_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.24", default-features = true }
tokio = { version = "1.21.1", features = ["full"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
rpi_embedded = "0.1.0"